ExerciseLogger: Person Class Reference
Person Class Reference
Public Member Functions
Person ()
void addExercise ()
void addData ()
string getName ()
int getAge ()
vector< Exericse * > getExercises ()
void printExercises ()
void display ()
void edit ()
void loadDataFromFile (ifstream &file)
Private Attributes
string name
int age
vector< Exericse * > exercises
Detailed Description
Definition at line 227 of file ExerciseLogger.cpp.
Constructor & Destructor Documentation
Person()
Person::Person () inline
Definition at line 234 of file ExerciseLogger.cpp.
{ age = 0; }
References age.
Member Function Documentation
addData()
void Person::addData () inline
function to add data from the user to the person object
Definition at line 280 of file ExerciseLogger.cpp.
    {
        cout << "Type in persons name" << endl;
        cin.ignore(1000, '\n');
        cin.clear();
        getline(cin, name);
        cout << "Type in persons age" << endl;
        cin >> age;
        addExercise();
    }
References addExercise(), age, and name.
Referenced by Menu::addNewPerson().
addExercise()
void Person::addExercise () inline
function to add exercises for a user
Definition at line 238 of file ExerciseLogger.cpp.
    {
        cout << "What type of exercise ?" << endl;
        cout << "1. Run " << endl;
        cout << "2. Weight Lifting" << endl;
        cout << "3. Hike" << endl;
        cout << "4. Swim" << endl;
        int userInput;
        cin >> userInput;
        if (userInput == 1)
        {
            cout << "Add info of most recent run" << endl;
            Run* run = new Run; //initiliase
            run->addData(); //add data
            exercises.push_back(run); //add to the vector
        }
        else if (userInput == 2)
        {
            cout << "Add info of most recent weightlifting" << endl;
            Weightlifting* wl = new Weightlifting; //initiliase
            wl->addData(); //add data
            exercises.push_back(wl); //add to the vector
        }
        else if (userInput == 3)
        {
            cout << "Add info of most recent Hike" << endl;
            Hike* hike = new Hike; //initiliase
            hike->addData(); //add data
            exercises.push_back(hike); //add to the vector
        }
        else if (userInput == 4)
        {
            cout << "Add info of most recent Swim" << endl;
            Swimming* swim = new Swimming; //initiliase
            swim->addData(); //add data
            exercises.push_back(swim); //add to the vector
        }
    }
References Run::addData(), Weightlifting::addData(), Swimming::addData(), and exercises.
Referenced by addData().
display()
void Person::display () inline
display function to show all user info
Definition at line 326 of file ExerciseLogger.cpp.
    {
        cout << "Name: " << name << " Age: " << age << endl;
        cout << "Exercises: " << endl;
        printExercises();
    }
References age, name, and printExercises().
edit()
void Person::edit () inline
edit function to edit the users info
Definition at line 335 of file ExerciseLogger.cpp.
    {
        cout << "Type in new name" << endl;
        cin.ignore(1000, '\n'); //clears the input buffer before using getline
        cin.clear();
        getline(cin, name);
        cout << "Type in new age" << endl;
        cin >> age;
    }
References age, and name.
getAge()
int Person::getAge () inline
function to return the age of the person
Definition at line 300 of file ExerciseLogger.cpp.
    {
        return age;
    }
References age.
getExercises()
vector< Exericse * > Person::getExercises () inline
function to return the exercises that the person has stored
Definition at line 307 of file ExerciseLogger.cpp.
    {
        return exercises;
    }
References exercises.
getName()
string Person::getName () inline
function to return the name of the person
Definition at line 293 of file ExerciseLogger.cpp.
    {
        return name;
    }
References name.
loadDataFromFile()
void Person::loadDataFromFile (ifstream & file) inline
loadDataFrom file, loads all the data from the file, and switched between exercise types
Definition at line 348 of file ExerciseLogger.cpp.
    {
        getline(file, name); //get the name, allows for spaces
        file >> age; //get the age
        int exerciseCount;
        file >> exerciseCount; //get the number of exercises from the file
        file.ignore(1000, '\n');
        file.clear();
        for(int i = 0 ;i< exerciseCount;i++)
        {
            int exerciseType;
            file >> exerciseType;
            switch (exerciseType)
            {
            case ExerciseType::RUN:
            {
                Run* run = new Run;
                run->loadDataFromFile(file); //call the load data from file for run
                exercises.push_back(run); //add the run to the vector
                break;
            }
            case ExerciseType::WEIGHT_LIFTING:
            {
                Weightlifting* wl = new Weightlifting;
                wl->loadDataFromFile(file); //call the load data from file for run
                exercises.push_back(wl); //add the run to the vector
                break;
            }
            case ExerciseType::HIKE:
            {
                Hike* hike = new Hike;
                hike->loadDataFromFile(file); //call the load data from file for run
                exercises.push_back(hike); //add the run to the vector
                break;
            }
            case ExerciseType::SWIMMING:
            {
                Swimming* swim = new Swimming;
                swim->loadDataFromFile(file); //call the load data from file for run
                exercises.push_back(swim); //add the run to the vector
                break;
            }
            default:
                break;
            }
            //assume there will always be one run
        }
    }
References age, exercises, HIKE, Run::loadDataFromFile(), Weightlifting::loadDataFromFile(), Swimming::loadDataFromFile(), name, RUN, SWIMMING, and WEIGHT_LIFTING.
Referenced by Menu::loadFromFile().
printExercises()
void Person::printExercises () inline
function to print the ecercises to the console;
Definition at line 314 of file ExerciseLogger.cpp.
    {
        for (int i = 0; i < exercises.size(); i++)
        {
            cout << "Exercise " << (i + 1) << endl;
            exercises[i]->display();
        }
        cout << endl;
    }
References exercises.
Referenced by display().
Member Data Documentation
age
int Person::age private
Definition at line 231 of file ExerciseLogger.cpp.
Referenced by addData(), display(), edit(), getAge(), loadDataFromFile(), and Person().
exercises
vector<Exericse*> Person::exercises private
Definition at line 232 of file ExerciseLogger.cpp.
Referenced by addExercise(), getExercises(), loadDataFromFile(), and printExercises().
name
string Person::name private
Definition at line 230 of file ExerciseLogger.cpp.
Referenced by addData(), display(), edit(), getName(), and loadDataFromFile().
The documentation for this class was generated from the following file:
ExerciseLogger/ExerciseLogger.cpp