ExerciseLogger: Menu Class Reference
Menu Class Reference
Public Member Functions
void start ()
Private Member Functions
void printPersonVector ()
void addNewPerson ()
void addNewExercise ()
void showPerson ()
void editPerson ()
void writeToFile ()
void loadFromFile ()
void saveAndQuit ()
Private Attributes
vector< Person > persons
bool keepMenuGoing = true
Detailed Description
Menu class, controls the program running, holds a vector of persons
Definition at line 406 of file ExerciseLogger.cpp.
Member Function Documentation
addNewExercise()
void Menu::addNewExercise () inline private
function to add a new run for a user, called from the main menu
Definition at line 434 of file ExerciseLogger.cpp.
    {
        cout << "Add exercise for which person?" << endl;
        printPersonVector();
        int input;
        cin >> input;
        persons[input - 1].addExercise();
    }
References persons, and printPersonVector().
Referenced by start().
addNewPerson()
void Menu::addNewPerson () inline private
function to add a new person
Definition at line 424 of file ExerciseLogger.cpp.
    {
        Person person; //initialize a person object
        person.addData(); //call the add data function;
        persons.push_back(person); // add to the vector stored in the menu object
    }
References Person::addData(), and persons.
Referenced by start().
editPerson()
void Menu::editPerson () inline private
function to edit person, called from the main menu
Definition at line 462 of file ExerciseLogger.cpp.
                      {
        cout << "Edit which person" << endl;
        printPersonVector();
        int input;
        cin >> input;
        persons[input - 1].edit();
    }
References persons, and printPersonVector().
Referenced by start().
loadFromFile()
void Menu::loadFromFile () inline private
function for loading all the info from a file
Definition at line 494 of file ExerciseLogger.cpp.
    {
        ifstream inputFile;
        inputFile.open(FILENAME); //open  file needed
        if (inputFile)
        {
            int personCount = 0;
            inputFile >> personCount; //get the number of people from the file
            inputFile.ignore(1000, '\n');
            inputFile.clear();
            for(int i = 0; i<personCount; i++)
            {
                Person person; //create a person object
                person.loadDataFromFile(inputFile);  //load data from file
                persons.push_back(person); //add the person to the vector
            }
        }
    }
References FILENAME, Person::loadDataFromFile(), and persons.
Referenced by start().
printPersonVector()
void Menu::printPersonVector () inline private
function to print person record
Definition at line 414 of file ExerciseLogger.cpp.
    {
        for (int i = 0; i < persons.size(); i++)
        {
            cout << (i + 1) << " " << persons[i].getName() << endl;
        }
    }
References persons.
Referenced by addNewExercise(), editPerson(), and showPerson().
saveAndQuit()
void Menu::saveAndQuit () inline private
Definition at line 513 of file ExerciseLogger.cpp.
    {
        writeToFile();
        keepMenuGoing = false;
        cout << "Goodbye" << endl;
    }
References keepMenuGoing, and writeToFile().
Referenced by start().
showPerson()
void Menu::showPerson () inline private
function to show person, called from the main menu
Definition at line 449 of file ExerciseLogger.cpp.
                      {
        cout << "Display which person" << endl;
        printPersonVector();
        int input;
        cin >> input;
        persons[input - 1].display();
    }
References persons, and printPersonVector().
Referenced by start().
start()
void Menu::start () inline
function to display the start menu
Definition at line 524 of file ExerciseLogger.cpp.
    {
        loadFromFile();
        while (keepMenuGoing)
        {
            cout << "Welcome to the Exercise logger, please choose an option" << endl;
            cout << "1. Add a new person" << endl;
            cout << "2. Add a new Exercise" << endl;
            cout << "3. Show Person" << endl;
            cout << "4. Edit Person" << endl;
            cout << "5. Write to File" << endl;
            cout << "6. Load from file" << endl;
            cout << "7. Save & Quit" << endl;
            int input;
            cin >> input;
            switch (input)
            {
            case 1:
                addNewPerson();
                break;
            case 2:
                addNewExercise();
                break;
            case 3:
                showPerson();
                break;
            case 4:
                editPerson();
                break;
            case 5:
                writeToFile();
                break;
            case 6:
                loadFromFile();
                break;
            case 7:
                saveAndQuit();
                break;
            }
        }
    }
References addNewExercise(), addNewPerson(), editPerson(), keepMenuGoing, loadFromFile(), saveAndQuit(), showPerson(), and writeToFile().
Referenced by main().
writeToFile()
void Menu::writeToFile () inline private
function for writing all the info to a file
Definition at line 475 of file ExerciseLogger.cpp.
    {
        ofstream outPutFile; //create output file objec
        outPutFile.open(FILENAME); //open the file wanted
        outPutFile << persons.size() << endl; //write the number of people to the file
        for (int i = 0; i < persons.size(); i++) //loop over all the person records
        {
            outPutFile << persons[i].getName() << endl; //send the name to the file
            outPutFile << persons[i].getAge() << endl; //send the age to the file
            outPutFile << persons[i].getExercises().size() << endl; //write the number of exercises to the file
            for (auto exercise : persons[i].getExercises()) //send all the runs to the file
            {
                outPutFile << exercise->getDataForFile() << endl;;
            }
        }
    }
References FILENAME, and persons.
Referenced by saveAndQuit(), and start().
Member Data Documentation
keepMenuGoing
bool Menu::keepMenuGoing = true private
Definition at line 410 of file ExerciseLogger.cpp.
Referenced by saveAndQuit(), and start().
persons
vector<Person> Menu::persons private
Definition at line 409 of file ExerciseLogger.cpp.
Referenced by addNewExercise(), addNewPerson(), editPerson(), loadFromFile(), printPersonVector(), showPerson(), and writeToFile().
The documentation for this class was generated from the following file:
ExerciseLogger/ExerciseLogger.cpp